Add support PHP 8.1
nanasess/setup-php pull request #62
Opened 2022-01-31 11:02 UTC by reindert-vetter

2022-01-31 16:23 UTC, nanasess requested changes

2022-01-31 16:23 UTC, nanasess commented on lib/apt-install-php-ubuntu.sh
> +if [[ $release = 'focal' && `echo "$version < 8.1" | bc` == 1 ]]
```suggestion
if [[ $release = 'focal' && `echo "$version < 8.0" | bc` == 1 ]]
```
The JSON and xmlrpc extensions exist only under PHP 8.0. This fix is probably unnecessary.
https://github.com/nanasess/setup-php/runs/5008646783?check_suite_focus=true#step:7:512

2022-01-31 16:25 UTC, nanasess commented
@reindert-vetter Welcome to setup-php, thanks for the Pull Request!
There is an error in GitHub Actions, please check it.

2022-02-01 15:27 UTC, nanasess commented
PHP8.0.3 build failure issue fixed in #63

2022-02-01 16:09 UTC, reindert-vetter commented
> PHP8.0.3 build failure issue fixed in #63

Thank you. I just looked at it, but I couldn't fix it.

2022-02-02 13:05 UTC, nanasess approved these changes

2022-02-02 13:06 UTC, merged

2022-02-02 13:06 UTC, nanasess commented
LGTM

2022-02-02 13:14 UTC, nanasess commented
@reindert-vetter 
Thanks you so much!, Fixed version has been released.
https://github.com/nanasess/setup-php/releases/tag/v3.0.9

2022-02-02 13:36 UTC, reindert-vetter commented
I really like this package to work. This package deserve more stars.